language: java

matrix:
  include:
    - os: linux
      jdk: openjdk8

script:
  - mvn -q -B -f currency-exchange-app/limits-service/pom.xml clean verify
  - mvn -q -B -f currency-exchange-app/config-service/pom.xml clean verify
